use super::{EnvKnob, EnvKnobValue, Flavor, Scope};

const PROTON: &[Scope] = &[Scope::Proton];
const PROTON_WINE: &[Scope] = &[Scope::Proton, Scope::Wine];
const ANY: &[Scope] = &[];
const GE_CACHY: &[Flavor] = &[Flavor::GeCachy];

/// Listed knob value with the env vars it sets.
const fn kv(
    value: &'static str,
    help: &'static str,
    env: &'static [(&'static str, &'static str)],
) -> EnvKnobValue {
    EnvKnobValue { value, help, env }
}

pub static KNOBS: &[EnvKnob] = &[
    // --- proton ------------------------------------------------------------
    EnvKnob {
        id: "proton-log",
        help: "Proton debug log to $PROTON_LOG_DIR/steam-$APPID.log. Sample: 1 (default channels) or warn+module.",
        scopes: PROTON,
        flavors: &[],
        freeform: Some("PROTON_LOG"),
        values: &[],
    },
    EnvKnob {
        id: "proton-wined3d",
        help: "Use OpenGL wined3d instead of Vulkan DXVK for D3D9/10/11. Sample: 1.",
        scopes: PROTON,
        flavors: &[],
        freeform: None,
        values: &[kv("1", "Use OpenGL-based wined3d instead of DXVK.", &[("PROTON_USE_WINED3D", "1")])],
    },
    EnvKnob {
        id: "proton-no-d3d11",
        help: "Disable d3d11.dll so D3D11 games fall back to D3D9. Sample: 1.",
        scopes: PROTON,
        flavors: &[],
        freeform: None,
        values: &[kv("1", "Disable d3d11.dll.", &[("PROTON_NO_D3D11", "1")])],
    },
    EnvKnob {
        id: "proton-no-esync",
        help: "Older Proton: disable eventfd-based in-process sync (esync). Sample: 1.",
        scopes: PROTON,
        flavors: &[],
        freeform: None,
        values: &[kv("1", "Do not use esync.", &[("PROTON_NO_ESYNC", "1")])],
    },
    EnvKnob {
        id: "proton-no-fsync",
        help: "Disable futex-based in-process sync (fsync). Sample: 1.",
        scopes: PROTON,
        flavors: &[],
        freeform: None,
        values: &[kv("1", "Do not use fsync.", &[("PROTON_NO_FSYNC", "1")])],
    },
    EnvKnob {
        id: "proton-no-ntsync",
        help: "Do not use the ntsync kernel module for in-process sync. Sample: 1.",
        scopes: PROTON,
        flavors: &[],
        freeform: None,
        values: &[kv("1", "Do not use ntsync.", &[("PROTON_NO_NTSYNC", "1")])],
    },
    EnvKnob {
        id: "proton-no-write-watch",
        help: "GE: disable ntdll memory write watches; helps specific games. Sample: 1.",
        scopes: PROTON,
        flavors: GE_CACHY,
        freeform: None,
        values: &[kv("1", "Disable write-watch support in ntdll.", &[("PROTON_NO_WRITE_WATCH", "1")])],
    },
    EnvKnob {
        id: "proton-wow64",
        help: "GE/CachyOS: run 32-bit games through WoW64. Sample: 1.",
        scopes: PROTON,
        flavors: &[],
        freeform: None,
        values: &[kv("1", "Enable wow64.", &[("PROTON_USE_WOW64", "1")])],
    },
    EnvKnob {
        id: "proton-large-address",
        help: "Force LARGE_ADDRESS_AWARE for all executables. Sample: 1.",
        scopes: PROTON,
        flavors: &[],
        freeform: None,
        values: &[kv("1", "Force LARGE_ADDRESS_AWARE.", &[("PROTON_FORCE_LARGE_ADDRESS_AWARE", "1")])],
    },
    EnvKnob {
        id: "proton-heap-delay-free",
        help: "Delay heap frees to work around use-after-free crashes. Sample: 1.",
        scopes: PROTON,
        flavors: &[],
        freeform: None,
        values: &[kv("1", "Delay freeing some memory.", &[("PROTON_HEAP_DELAY_FREE", "1")])],
    },
    EnvKnob {
        id: "proton-old-gl-string",
        help: "Limit the GL extension string length for old games that crash on it. Sample: 1.",
        scopes: PROTON,
        flavors: &[],
        freeform: None,
        values: &[kv("1", "Limit GL extension string length.", &[("PROTON_OLD_GL_STRING", "1")])],
    },
    EnvKnob {
        id: "proton-nvapi",
        help: "Enable NVAPI (DLSS, G-Sync, frame gen). GE default; official Proton needs this. Sample: 1.",
        scopes: PROTON,
        flavors: &[],
        freeform: None,
        values: &[kv("1", "Enable the NVAPI GPU support library.", &[("PROTON_ENABLE_NVAPI", "1")])],
    },
    EnvKnob {
        id: "proton-nvapi-off",
        help: "Disable NVAPI, for games that break with it. Sample: 1.",
        scopes: PROTON,
        flavors: &[],
        freeform: None,
        values: &[kv("1", "Disable the NVAPI GPU support library.", &[("PROTON_DISABLE_NVAPI", "1")])],
    },
    EnvKnob {
        id: "proton-hide-nvidia-gpu",
        help: "Report the GPU as AMD for games with Windows-only NVIDIA checks. Sample: 1.",
        scopes: PROTON,
        flavors: &[],
        freeform: None,
        values: &[kv("1", "Report NVIDIA GPUs as AMD GPUs.", &[("PROTON_HIDE_NVIDIA_GPU", "1")])],
    },
    EnvKnob {
        id: "proton-ngx-updater",
        help: "Allow DLSS NGX updates to download inside the prefix. Sample: 1.",
        scopes: PROTON,
        flavors: &[],
        freeform: None,
        values: &[kv("1", "Enable the NGX DLSS updater.", &[("PROTON_ENABLE_NGX_UPDATER", "1")])],
    },
    EnvKnob {
        id: "proton-wayland",
        help: "GE/CachyOS/newer Proton: use the Wine-Wayland driver instead of X11. Sample: 1.",
        scopes: PROTON,
        flavors: GE_CACHY,
        freeform: None,
        values: &[kv("1", "Enable the Wayland driver.", &[("PROTON_ENABLE_WAYLAND", "1")])],
    },
    EnvKnob {
        id: "proton-hdr",
        help: "GE/Proton Experimental: enable HDR; needs compositor + game + monitor support. Sample: 1.",
        scopes: PROTON,
        flavors: GE_CACHY,
        freeform: None,
        values: &[kv("1", "Enable HDR.", &[("PROTON_ENABLE_HDR", "1")])],
    },
    EnvKnob {
        id: "proton-sdl-input",
        help: "Prefer SDL input over HIDRAW/Steam Input; helps controllers under Wine-Wayland. Sample: 1.",
        scopes: PROTON,
        flavors: &[],
        freeform: None,
        values: &[kv("1", "Use SDL input instead of HIDRAW/Steam Input.", &[("PROTON_USE_SDL", "1")])],
    },
    EnvKnob {
        id: "proton-fsr4",
        help: "GE/CachyOS: upgrade FSR 3.1 games to FSR 4; 1 or a version. Sample: 4.0.2.",
        scopes: PROTON,
        flavors: GE_CACHY,
        freeform: Some("PROTON_FSR4_UPGRADE"),
        values: &[],
    },
    EnvKnob {
        id: "proton-dlss-upgrade",
        help: "GE/CachyOS: download newer DLSS DLLs; 1 or a version. Sample: 310.2.",
        scopes: PROTON,
        flavors: GE_CACHY,
        freeform: Some("PROTON_DLSS_UPGRADE"),
        values: &[],
    },
    EnvKnob {
        id: "proton-xess-upgrade",
        help: "GE/CachyOS: download newer XeSS DLLs. Sample: 1.",
        scopes: PROTON,
        flavors: GE_CACHY,
        freeform: None,
        values: &[kv("1", "Upgrade XeSS DLLs.", &[("PROTON_XESS_UPGRADE", "1")])],
    },
    EnvKnob {
        id: "proton-local-shader-cache",
        help: "GE/CachyOS: keep the shader cache in the prefix. Sample: 1.",
        scopes: PROTON,
        flavors: GE_CACHY,
        freeform: None,
        values: &[kv("1", "Use a prefix-local shader cache.", &[("PROTON_LOCAL_SHADER_CACHE", "1")])],
    },
    EnvKnob {
        id: "proton-nvidia-libs",
        help: "GE/CachyOS: use Proton's NVIDIA libraries. Sample: 1.",
        scopes: PROTON,
        flavors: GE_CACHY,
        freeform: None,
        values: &[kv("1", "Enable Proton NVIDIA libs.", &[("PROTON_NVIDIA_LIBS", "1")])],
    },
    EnvKnob {
        id: "proton-nvidia-libs-no-32bit",
        help: "GE/CachyOS: Proton NVIDIA libs without 32-bit. Sample: 1.",
        scopes: PROTON,
        flavors: GE_CACHY,
        freeform: None,
        values: &[kv("1", "Skip 32-bit NVIDIA libs.", &[("PROTON_NVIDIA_LIBS_NO_32BIT", "1")])],
    },
    EnvKnob {
        id: "proton-nvidia-nvoptix",
        help: "GE/CachyOS: enable NV OptiX. Sample: 1.",
        scopes: PROTON,
        flavors: GE_CACHY,
        freeform: None,
        values: &[kv("1", "Enable NV OptiX.", &[("PROTON_NVIDIA_NVOPTIX", "1")])],
    },
    EnvKnob {
        id: "steamdeck-spoof",
        help: "Spoof a Steam Deck so games unlock Deck features. Sample: 1.",
        scopes: ANY,
        flavors: &[],
        freeform: None,
        values: &[kv("1", "Set SteamDeck=1.", &[("SteamDeck", "1")])],
    },
    // --- wine (plain Wine and Proton) ---------------------------------------
    EnvKnob {
        id: "wine-dlloverrides",
        help: "Wine DLL load-order overrides. Sample: d3d11=n,b;dxgi=n.",
        scopes: PROTON_WINE,
        flavors: &[],
        freeform: Some("WINEDLLOVERRIDES"),
        values: &[],
    },
    EnvKnob {
        id: "wine-debug",
        help: "Wine debug channels. Sample: -all (quiet) or warn+module.",
        scopes: PROTON_WINE,
        flavors: &[],
        freeform: Some("WINEDEBUG"),
        values: &[],
    },
    EnvKnob {
        id: "wine-sync",
        help: "In-process sync primitive for plain Wine. Sample: fsync.",
        scopes: PROTON_WINE,
        flavors: &[],
        freeform: None,
        values: &[
            kv("esync", "Use esync (eventfd).", &[("WINEESYNC", "1")]),
            kv("fsync", "Use fsync (futex2).", &[("WINEFSYNC", "1")]),
            kv("ntsync", "Use the ntsync kernel module.", &[("WINENTSYNC", "1")]),
        ],
    },
    EnvKnob {
        id: "wine-fsr",
        help: "GE: AMD FSR upscaling for fullscreen Vulkan games. Sample: 1.",
        scopes: PROTON_WINE,
        flavors: &[],
        freeform: None,
        values: &[kv("1", "Enable FSR fullscreen upscale.", &[("WINE_FULLSCREEN_FSR", "1")])],
    },
    EnvKnob {
        id: "wine-integer-scaling",
        help: "Sharp integer upscaling in Wine/Proton. Sample: 1.",
        scopes: PROTON_WINE,
        flavors: &[],
        freeform: None,
        values: &[kv("1", "Enable integer scaling.", &[("WINE_FULLSCREEN_INTEGER_SCALING", "1")])],
    },
    // --- dxvk ---------------------------------------------------------------
    EnvKnob {
        id: "dxvk-hud",
        help: "DXVK overlay. Sample: full, 1 (devinfo+fps), or 0.",
        scopes: PROTON_WINE,
        flavors: &[],
        freeform: None,
        values: &[
            kv("1", "Default HUD (devinfo,fps).", &[("DXVK_HUD", "1")]),
            kv("full", "All HUD elements.", &[("DXVK_HUD", "full")]),
            kv("0", "Disable the HUD.", &[("DXVK_HUD", "0")]),
        ],
    },
    EnvKnob {
        id: "dxvk-config",
        help: "Inline DXVK config (dxvk.conf syntax, ';' separated). Sample: dxgi.hideAmdGpu = True.",
        scopes: PROTON_WINE,
        flavors: &[],
        freeform: Some("DXVK_CONFIG"),
        values: &[],
    },
    EnvKnob {
        id: "dxvk-async",
        help: "gplasync forks only: async shader compilation; not for stock DXVK. Sample: 1.",
        scopes: PROTON_WINE,
        flavors: &[],
        freeform: None,
        values: &[kv("1", "Enable async shader compilation.", &[("DXVK_ASYNC", "1")])],
    },
    EnvKnob {
        id: "dxvk-filter-device",
        help: "Force DXVK to a Vulkan device by name substring. Sample: RADV.",
        scopes: PROTON_WINE,
        flavors: &[],
        freeform: Some("DXVK_FILTER_DEVICE_NAME"),
        values: &[],
    },
    EnvKnob {
        id: "dxvk-vkreflex",
        help: "dxvk-nvapi: Vulkan Reflex layer for Reflex-in-Vulkan games. Sample: 1.",
        scopes: PROTON_WINE,
        flavors: &[],
        freeform: None,
        values: &[kv("1", "Enable the Vulkan Reflex layer.", &[("DXVK_NVAPI_VKREFLEX", "1")])],
    },
    // --- vkd3d-proton ---------------------------------------------------------
    EnvKnob {
        id: "vkd3d-config",
        help: "vkd3d-proton options, comma separated. Sample: dxr,single_queue.",
        scopes: PROTON_WINE,
        flavors: &[],
        freeform: Some("VKD3D_CONFIG"),
        values: &[],
    },
    EnvKnob {
        id: "vkd3d-framerate",
        help: "Cap the D3D12 frame rate. Sample: 60 (0 uncaps).",
        scopes: PROTON_WINE,
        flavors: &[],
        freeform: Some("VKD3D_FRAME_RATE"),
        values: &[],
    },
    EnvKnob {
        id: "vkd3d-present-mode",
        help: "Force the Vulkan present mode for D3D12. Sample: MAILBOX.",
        scopes: PROTON_WINE,
        flavors: &[],
        freeform: None,
        values: &[
            kv("IMMEDIATE", "Immediate (uncapped, tearing).", &[("VKD3D_SWAPCHAIN_PRESENT_MODE", "IMMEDIATE")]),
            kv("MAILBOX", "Mailbox.", &[("VKD3D_SWAPCHAIN_PRESENT_MODE", "MAILBOX")]),
            kv("FIFO", "FIFO (vsync).", &[("VKD3D_SWAPCHAIN_PRESENT_MODE", "FIFO")]),
            kv("FIFO_RELAXED", "Relaxed FIFO.", &[("VKD3D_SWAPCHAIN_PRESENT_MODE", "FIFO_RELAXED")]),
            kv("FIFO_LATEST_READY", "FIFO latest ready.", &[("VKD3D_SWAPCHAIN_PRESENT_MODE", "FIFO_LATEST_READY")]),
        ],
    },
    // --- mangohud (scopeless) -------------------------------------------------
    EnvKnob {
        id: "mangohud",
        help: "Enable the MangoHud Vulkan overlay. Sample: 1. Composes with the MangoHud argv wrapper; either one enables the overlay.",
        scopes: ANY,
        flavors: &[],
        freeform: None,
        values: &[kv("1", "Enable MangoHud.", &[("MANGOHUD", "1")])],
    },
    EnvKnob {
        id: "mangohud-config",
        help: "MangoHud options, comma separated. Sample: fps_limit=60,position=top-right.",
        scopes: ANY,
        flavors: &[],
        freeform: Some("MANGOHUD_CONFIG"),
        values: &[],
    },
    // --- mesa -----------------------------------------------------------------
    EnvKnob {
        id: "mesa-present-mode",
        help: "Override the Vulkan present mode on Mesa drivers. Sample: mailbox.",
        scopes: ANY,
        flavors: &[],
        freeform: None,
        values: &[
            kv("fifo", "FIFO (vsync).", &[("MESA_VK_WSI_PRESENT_MODE", "fifo")]),
            kv("relaxed", "Relaxed FIFO.", &[("MESA_VK_WSI_PRESENT_MODE", "relaxed")]),
            kv("mailbox", "Mailbox.", &[("MESA_VK_WSI_PRESENT_MODE", "mailbox")]),
            kv("immediate", "Immediate (uncapped, tearing).", &[("MESA_VK_WSI_PRESENT_MODE", "immediate")]),
        ],
    },
    EnvKnob {
        id: "mesa-shader-cache-size",
        help: "Mesa on-disk shader cache size. Sample: 10G.",
        scopes: ANY,
        flavors: &[],
        freeform: Some("MESA_SHADER_CACHE_MAX_SIZE"),
        values: &[],
    },
    EnvKnob {
        id: "mesa-driver-override",
        help: "Force a Mesa driver. Sample: zink (OpenGL on Vulkan).",
        scopes: ANY,
        flavors: &[],
        freeform: Some("MESA_LOADER_DRIVER_OVERRIDE"),
        values: &[],
    },
    EnvKnob {
        id: "mesa-gl-version",
        help: "Report a different GL version for old games. Sample: 4.6COMPAT.",
        scopes: ANY,
        flavors: &[],
        freeform: Some("MESA_GL_VERSION_OVERRIDE"),
        values: &[],
    },
    EnvKnob {
        id: "mesa-anti-lag",
        help: "Mesa 25.3+ AMD: enable the VK_AMD_anti_lag layer. Sample: 1.",
        scopes: ANY,
        flavors: &[],
        freeform: None,
        values: &[kv("1", "Enable the Mesa anti-lag layer.", &[("ENABLE_LAYER_MESA_ANTI_LAG", "1")])],
    },
    EnvKnob {
        id: "vblank-mode",
        help: "Mesa OpenGL vsync (driconf). Sample: 0.",
        scopes: ANY,
        flavors: &[],
        freeform: None,
        values: &[
            kv("0", "Disable vsync (swap interval 0).", &[("vblank_mode", "0")]),
            kv("1", "Initial swap interval 0; obey the app's choice.", &[("vblank_mode", "1")]),
            kv("2", "Initial swap interval 1; obey the app's choice.", &[("vblank_mode", "2")]),
            kv("3", "Force swap interval 1 (vsync); overrides the app.", &[("vblank_mode", "3")]),
        ],
    },
    // --- amd ------------------------------------------------------------------
    EnvKnob {
        id: "radv-perftest",
        help: "RADV perf-test features, comma separated. Sample: sam,nggc.",
        scopes: ANY,
        flavors: &[],
        freeform: Some("RADV_PERFTEST"),
        values: &[],
    },
    EnvKnob {
        id: "radv-debug",
        help: "RADV debug flags, comma separated. Sample: nofastclears.",
        scopes: ANY,
        flavors: &[],
        freeform: Some("RADV_DEBUG"),
        values: &[],
    },
    EnvKnob {
        id: "radv-force-vrs",
        help: "Force vertex shading rate (GFX10.3+). Sample: 2x2.",
        scopes: ANY,
        flavors: &[],
        freeform: None,
        values: &[
            kv("2x2", "2x2 shading rate.", &[("RADV_FORCE_VRS", "2x2")]),
            kv("1x2", "1x2 shading rate.", &[("RADV_FORCE_VRS", "1x2")]),
            kv("2x1", "2x1 shading rate.", &[("RADV_FORCE_VRS", "2x1")]),
            kv("1x1", "1x1 (no change).", &[("RADV_FORCE_VRS", "1x1")]),
        ],
    },
    EnvKnob {
        id: "amd-debug",
        help: "RadeonSI OpenGL debug flags, comma separated. Sample: nodcc.",
        scopes: ANY,
        flavors: &[],
        freeform: Some("AMD_DEBUG"),
        values: &[],
    },
    EnvKnob {
        id: "dri-prime",
        help: "Mesa GPU selection. Sample: 1 or pci-0000_03_00_0 (append ! to hide others).",
        scopes: ANY,
        flavors: &[],
        freeform: Some("DRI_PRIME"),
        values: &[],
    },
    // --- intel ----------------------------------------------------------------
    EnvKnob {
        id: "anv-debug",
        help: "Intel ANV (Vulkan) flags, comma separated. Sample: no-gpl.",
        scopes: ANY,
        flavors: &[],
        freeform: Some("ANV_DEBUG"),
        values: &[],
    },
    EnvKnob {
        id: "intel-debug",
        help: "Intel Mesa OpenGL debug flags, comma separated. Sample: nofc.",
        scopes: ANY,
        flavors: &[],
        freeform: Some("INTEL_DEBUG"),
        values: &[],
    },
    // --- nvidia ---------------------------------------------------------------
    EnvKnob {
        id: "nvidia-prime-offload",
        help: "Run on the NVIDIA GPU via PRIME render offload (GLX+EGL+Vulkan). Sample: offload.",
        scopes: ANY,
        flavors: &[],
        freeform: None,
        values: &[kv("offload", "PRIME render offload to the NVIDIA GPU.", &[("__NV_PRIME_RENDER_OFFLOAD", "1"), ("__GLX_VENDOR_LIBRARY_NAME", "nvidia"), ("__VK_LAYER_NV_optimus", "NVIDIA_only")])],
    },
    EnvKnob {
        id: "nvidia-vrr",
        help: "Allow G-Sync/VRR for OpenGL applications. Sample: 1.",
        scopes: ANY,
        flavors: &[],
        freeform: None,
        values: &[
            kv("1", "Allow VRR.", &[("__GL_VRR_ALLOWED", "1")]),
            kv("0", "Disable VRR.", &[("__GL_VRR_ALLOWED", "0")]),
        ],
    },
    EnvKnob {
        id: "nvidia-vsync-gl",
        help: "NVIDIA OpenGL vsync. Sample: 0 (uncapped).",
        scopes: ANY,
        flavors: &[],
        freeform: None,
        values: &[
            kv("0", "Disable GL vsync.", &[("__GL_SYNC_TO_VBLANK", "0")]),
            kv("1", "Enable GL vsync.", &[("__GL_SYNC_TO_VBLANK", "1")]),
        ],
    },
    EnvKnob {
        id: "nvidia-threaded-gl",
        help: "NVIDIA threaded GL optimizations; breaks apps relying on synchronous GL. Sample: 1.",
        scopes: ANY,
        flavors: &[],
        freeform: None,
        values: &[
            kv("1", "Enable threaded optimizations.", &[("__GL_THREADED_OPTIMIZATIONS", "1")]),
            kv("0", "Disable threaded optimizations.", &[("__GL_THREADED_OPTIMIZATIONS", "0")]),
        ],
    },
    EnvKnob {
        id: "nvidia-shader-cache-skip-cleanup",
        help: "Keep the NVIDIA GL shader cache instead of cleaning it up. Sample: 1.",
        scopes: ANY,
        flavors: &[],
        freeform: None,
        values: &[kv("1", "Skip shader cache cleanup.", &[("__GL_SHADER_DISK_CACHE_SKIP_CLEANUP", "1")])],
    },
    EnvKnob {
        id: "nvidia-shader-cache-size",
        help: "NVIDIA GL on-disk shader cache size in bytes. Sample: 10737418240.",
        scopes: ANY,
        flavors: &[],
        freeform: Some("__GL_SHADER_DISK_CACHE_SIZE"),
        values: &[],
    },
    // --- general --------------------------------------------------------------
    EnvKnob {
        id: "malloc-arena-max",
        help: "glibc malloc arena count; lower trims virtual memory. Sample: 2.",
        scopes: ANY,
        flavors: &[],
        freeform: Some("MALLOC_ARENA_MAX"),
        values: &[],
    },
    EnvKnob {
        id: "low-latency-layer",
        help: "Korthos low_latency_layer (shipped by proton-cachyos): input-latency reduction. Sample: 1.",
        scopes: ANY,
        flavors: &[],
        freeform: None,
        values: &[kv("1", "Enable low_latency_layer.", &[("LOW_LATENCY_LAYER", "1")])],
    },
    EnvKnob {
        id: "low-latency-layer-reflex",
        help: "CachyOS low_latency_layer Reflex path. Sample: 1.",
        scopes: ANY,
        flavors: GE_CACHY,
        freeform: None,
        values: &[kv("1", "Enable the Reflex low-latency layer.", &[("LOW_LATENCY_LAYER_REFLEX", "1")])],
    },
];
